### PR TITLE
Solving the problem of not being able to jump normally under window

### PR DESCRIPTION
**Pull request by 11a222**
Solving the problem of not being able to jump normally under window,Because I displayed 'data-v-inspector="srciewshomecomponentsTitleindex.tsx:21:22"' in the window,The performance of other systems has not been tested yet.

### CODE REVIEW

**Comment by webfansplz** [comment]
This will make the injected path difficult to read.

Can you provide a mini repo ? I didn't find this issue with Windows.

**Comment by 11a222** [comment]
> This will make the injected path difficult to read.
> 
> Can you provide a mini repo ? I didn't find this issue with Windows.

You can solve the problem of difficulty reading by using decode on Overlay.vue. I have tried several computers and this is the case

vite.config.js


```

import { defineConfig } from 'vite'
import Vue from '@vitejs/plugin-vue'
import Inspector from 'vite-plugin-vue-inspector'

export default defineConfig({
  plugins: [
    Vue(),
    Inspector({
      toggleButtonVisibility: 'always',
      toggleComboKey: 'ctrl',
    }),
  ],
})


```

**Comment by webfansplz** [comment]
Can you upgrade to v3.4.2 and try again?

**Comment by 11a222** [comment]
3.4.2 No problem

**Pull request closed without merging**
